### ISSUE TITLE
Unknown modifier

### ISSUE THREAD

**Issue by melanietreitinger** [rezeau/moodle-qtype_regexp#11]
I get the following error:
"PHP Warning:  preg_match(): Unknown modifier... in moodle/question/type/regexp/question.php on line 194"

This indicates that the delimiter occurs in the string to be matched - so it needs to be escaped e.g. by using preg_quote(). 

This might also apply to other parts of the code.

Wo you be so kind and look into this?

**Comment by rezeau** [comment]
Please provide one (or more) examples of the question text that triggers that PHP Warning.

**Comment by melanietreitinger** [comment]
It's the regex that causes the error - one example is the following code, containing a slash in the regex:
`preg_match('/^/foo$/ui', 'teststring')`

Using preg_quote() fixes this:
`preg_match('/^'.preg_quote('/foo', '/').'$/ui', 'teststring')`

**Comment by rezeau** [comment]
Thanks for the reply, but what I really need is a real-world example of your question. Please export your "problematic" REGEXP question in MOODLE XML format and attach it to your reply.

**Comment by melanietreitinger** [comment]
Sorry for the late reply!
It turns out that the question causing this error is of type "essayautograde"! I wonder how this can trigger a function within `question/type/regexp/question.php`!
But the weirdest thing is that I cannot reproduce the error by exporting/importing the question - I can reproduce it only in the original course. 

So, unless you consider it useful anyway to add preg_quote() you can close this issue. Thanks!

**Comment by rezeau** [comment]
This is really strange! I'll enquire, but will close this issue for now.
