### ISSUE TITLE
calculate alternate answers doesn't work with answers that use < symbol

### ISSUE THREAD

**Issue by jboulen** [rezeau/moodle-qtype_regexp#12]
Hello,

When you calculate alternate answers, with an answer like `0<1`, then, everything after `<` is removed.

I think it's because [this line](https://github.com/rezeau/moodle-qtype_regexp/blob/20d6d1d9fc49bde033621282317c0bf4f377e63a/edit_regexp_form.php#L49) uses the argument `PARAM_NOTAGS`.

On my testing server, I replaced `PARAM_NOTAGS` by `PARAM_RAW`. Then, before [this line](https://github.com/rezeau/moodle-qtype_regexp/blob/20d6d1d9fc49bde033621282317c0bf4f377e63a/edit_regexp_form.php#L101), I inserted the following code to escape HTML code : `$answer = s($answer);`.

Do you think it's a good approach to resolve this issue ? If it seems good for you, I can create a pull request.

Regards,

**Comment by rezeau** [comment]
Bonjour Julien !
I don't understand your problem. Please contact me by PM on the [French Moodle forum](https://moodle.org/course/view.php?id=20).

**Comment by rezeau** [comment]
closed
