### ISSUE TITLE
Hints not importing with Moodle XML

### ISSUE THREAD

**Issue by gboye** [rezeau/moodle-qtype_regexp#16]
I am trying to import regexp questions with a Moodle XML file. Everything works fine except for the hints that don't get imported. I tried exporting a regexp question with hints, it works fine but when importing back into the bank, the hints don't import either...

I'm not sure where to ask for help...

Gilles

**Comment by rezeau** [comment]
@gboye Well-spotted! The Hints are correctly exported but not imported. The reason being that the REGEXP question type already provides lots of meaningful feedback, and I did not consider hints to be necessary. I will fix this as soon as possible.

**Comment by rezeau** [comment]
Fixed

**Comment by gboye** [comment]
Thanks very much (merci beaucoup).
