### ISSUE TITLE
expensive regexp fail with server error 500

### ISSUE THREAD

**Issue by a-kempka** [rezeau/moodle-qtype_regexp#17]
When using a regexp that could have many potential correct answers (e.g. `[A-Za-z][A-Za-z][A-Za-z][A-Za-z][A-Za-z][A-Za-z][A-Za-z]`) a teacher cannot see the preview of the question, nor can a student take the question as a HTTP 500 internal server error occurrs after a long delay. This effectively makes the question unusable and there are no means to prevent such regexp from the admins' perspective.

The question type is very tempting to use for us, but for the usage in summative assessment this is highly problematic.
 
Could you provide a way to either
* impose a configurable limit on the complexity of the regexp?
* optionally limit the question type to only evaluate the regexp against the answer given and (possibly) not generate all possible answers?

**Comment by rezeau** [comment]
@a-kempka I am well aware of the limits of my regexp Moodle question type. If you want to further discuss this matter please contact me at my e-mail address to be found in [my Moodle profile](https://moodle.org/user/profile.php?id=20216).
