### ISSUE TITLE
Regex dots, braces, etc

### ISSUE THREAD

**Issue by RyanNutt** [rezeau/moodle-qtype_regexp#2]
Is there a way to use braces and periods as part of the regex, or am I just missing something?

What I'm trying to do is use regex to match for short answer Java or Python questions where spaces don't really matter. Ex: If they type x == 2, it really doesn't matter if there's a space or 100 spaces between the x and the ==.

Right now I'm using x ?== ?2 to match one or zero spaces, but it would be better if I could do something like x .== .2 where it would match any number of spaces. That could potentially make for an unlimited number work correct solutions though. I've also tried x {0,10}== {0,10}2 to allow for between 0 and 10 spaces thinking that might work. In both cases it came back with an error that I needed to escape the . or the { and }.

**Comment by rezeau** [comment]
Le 17/03/2015 18:45, Ryan Nutt a
      écrit :
    
    
      Is there a way to use braces and periods as part of the regex,
        or am I just missing something?
      What I'm trying to do is use regex to match for short answer
        Java or Python questions where spaces don't really matter. Ex:
        If they type x == 2, it really doesn't matter if there's a space
        or 100 spaces between the x and the ==.
      Right now I'm using x ?== ?2 to match one or zero spaces, but
        it would be better if I could do something like x .== .2 where
        it would match any number of spaces. That could potentially make
        for an unlimited number work correct solutions though. I've also
        tried x {0,10}== {0,10}2 to allow for between 0 and 10 spaces
        thinking that might work. In both cases it came back with an
        error that I needed to escape the . or the { and }. 
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    Hi Ryan and thanks for your interest in my REGEXP question type.
    However, I have now stopped all work on the Moodle platform, and am
    spending my retirement working in my garden.
    Sorry to be unable to help,
    Joseph
