### ISSUE TITLE
Fatal error in today's latest code

### ISSUE THREAD

**Issue by aspark21** [rezeau/moodle-qtype_regexp#20]
PHP Fatal error:  Uncaught ParseError: syntax error, unexpected variable "$formdata", expecting ")" in /var/www/html/question/type/regexp/tests/question_type_test.php:116

https://github.com/rezeau/moodle-qtype_regexp/blob/master/tests/question_type_test.php#L116

Causes full PHPUnit suite to crash out early.
Moodle 4.3
PHP8.1

**Comment by rezeau** [comment]
@aspark21 Thanks for your comment and PR. Sorry I released this version without full checking. I had so many cibot warnings to fix that I make a few mistakes. I am fixing them now and will hopefully release a correct version later today! In the meantime I have hidden version 2024050200 to prevent this buggy release from being installed!

**Comment by aspark21** [comment]
No worries, we’re always testing bleeding edge on GitHub with the full test suite so used to catching & reporting things the moodle-plugin-ci GitHub Actions might not catch

**Comment by aspark21** [comment]
Have kicked off a couple of runs, seem to be getting pass the point where the Fatal errors were occurring so will close this off. Will let you know if it throws anything else.

Thanks!
