### ISSUE TITLE
Combination Regex and cloze question type in Moodle

### ISSUE THREAD

**Issue by gergelyrakoczi** [rezeau/moodle-qtype_regexp#23]
Hi Joseph,
great plugin, we are using it for years now. I have a question. According to the Moodle documentation, the combination of Regex and the question type "Cloze" should work, however we do not get it running.
https://docs.moodle.org/404/en/Embedded_Answers_(Cloze)_question_type
Have you some working examples here? Are there issues or bugs known? I welcome any information on this topic.
Thank you and best regards from TU Wien!
Gergely

**Comment by rezeau** [comment]
Fixed by the creation of a new question type https://github.com/rezeau/moodle-qtype_multianswerrgx
