### ISSUE TITLE
Checking short answer for programming language

### ISSUE THREAD

**Issue by demidovsursu** [rezeau/moodle-qtype_regexp#4]
I seen previous issue about checking answer for Python or Java. I encountered the same problem.

I see another way to solve this problem.
First need to separate student's answer to words ([a-zA-Z0-9]+) and other chars ([^ a-zA-Z0-9]). 
"a1==b1" become "a1 = = b1", then compare with 1 correct answer, which separated in the same way. Regexp answers should be separated by author of question: (b1 = = a1|a1 = = b1).

And need to add new setting for that behavior (Separate answer to words and punctuation: on/off).

**Comment by rezeau** [comment]
The RegExp Short Answer question is meant to be used with questions requiring **natural language** answers. This question type is not well-suited to questions requiring mathematical, scientific, programming "languages".

**Comment by demidovsursu** [comment]
Student can skip a space after punctuation in the natural language answer. 
For example, "It's blue,white,red"

Need changes in function compare_response_with_answer:
```
        if ($this->separateword) {
            $correctresponse = $this->get_correct_response();
            if (separate_words($response['answer'],$this->usecase) == separate_words($correctresponse['answer'],$this->usecase)) {
                return true;
            }
        }
```
where
```
function separate_words($text, $usecase) {
  $text=preg_replace('/([a-zA-Z0-9])([^ a-zA-Z0-9])/','$1 $2',$text);
  $text=preg_replace('/([^ a-zA-Z0-9])([a-zA-Z0-9])/','$1 $2',$text);
  $text=preg_replace('/([^ a-zA-Z0-9])([^ a-zA-Z0-9])/','$1 $2',$text);
  if(!$usecase) $text=strtoupper($text);
  return $text;
}
```

**Comment by rezeau** [comment]
"Student can skip a space after punctuation in the natural language answer.
For example, "It's blue,white,red""
Well, that answer (missing spaces) is obviously analysed as _incorrect_ in natural language.

**Comment by demidovsursu** [comment]
Another reason.
Student may use the wrong case. For example, there are two mistakes in the phrase "today is monday", but  you can switch off the option "Case sensitivity" to ignore case.

Why not make the option to ignore missing spaces?
(where "ignore" is "insert the spaces into all possible places - before and after any punctuation")

**Comment by rezeau** [comment]
Why not make the option to ignore missing spaces?
Because, in natural language, spaces cannot be ignored.
