### ISSUE TITLE
no MOODLE_39_STABLE branch

### ISSUE THREAD

**Issue by durzo** [rezeau/moodle-qtype_regexp#8]
you have branches for 37, 38 and then 310.. which branch do we use for 3.9 ?

**Comment by rezeau** [comment]
Sorry about "jumping over" moodle 3.9. You can use my 38 branch if you have moodle 3.8.

**Comment by durzo** [comment]
and if we have moodle 3.9?

**Comment by rezeau** [comment]
Sorry again, I meant the 38 branch is OK for use with Moodle 3.8 _and_ Moodle 3.9.
